name: intl_generator
version: 1.0.1
publish_to: https://pub.trugman.com/
description: >-
  Contains code to deal with internationalized/localized messages,
  date and number formatting and parsing, bi-directional text, and
  other internationalization issues.

homepage: https://github.com/kiwi-bop/intl_generator
environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  collection: ">=1.15.0 <2.0.0"
  analyzer: ^4.1.0
  args: ">=2.1.0 <3.0.0"
  dart_style: ^2.2.0
  intl: ">=0.17.0 <0.20.0"
  path: ">=1.8.0 <2.0.0"
  petitparser: ^4.3.0
dev_dependencies:
  test: ^1.17.12
